Algoritmo "laço de repedição"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   Jailson 
// Descrição   : uso de laco de repetilão
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis 
  contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   enquanto contador<10 faca
  escreval("teste")
  contador<-contador+1
  fimenquanto
Fimalgoritmo