Algoritmo "manzano02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis 
   numero

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite um nnumero :")
 leia (numero)

Fimalgoritmo