Algoritmo "mazeno-para"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis 
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 10 passo 1 faca
escreval(contador)
fimpara
Fimalgoritmo