Algoritmo "sucessor"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson
// Descrição   : solicitação de um valor exibir o seu sucessor
// Autor(a)    : Vitor
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite um valor ")
 leia(valor)
 valor<- valor+1
 escreva ("o valor sucesor a esse é: ",valor)
Fimalgoritmo